FROM alpine:latest as alpine
RUN apk --update add ca-certificates
RUN apk --update add mailcap

VOLUME /srv
EXPOSE 80

COPY .docker.json /.filecloud.json
COPY filecloud /filecloud

ENTRYPOINT [ "/filecloud" ]
